#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import json
import math
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
EXPECTED_WORKLOADS = {
    "layernorm_backward",
    "weighted_var_backward",
    "pearson_backward",
    "softmax_logits_backward",
    "lars_momentum",
    "rowwise_quant",
}
EXPECTED_WIDTHS = {4096, 8192, 16384, 32768, 65536}
REQUIRED_RESULT_FILES = {
    "REPORT.md",
    "cluster_sweep.csv",
    "control_raw.csv",
    "cuda_raw.csv",
    "framework_raw.json",
    "metadata.json",
    "summary.csv",
}
REQUIRED_SOURCE_FILES = {
    "src/primitive_benchmark.cu",
    "src/cluster_control.cu",
    *(f"src/workloads/{name}.cu" for name in EXPECTED_WORKLOADS),
}


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as source:
        return list(csv.DictReader(source))


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Validate one complete RTX 5090 bundle and one complete H100 bundle."
    )
    parser.add_argument("runs", nargs=2, type=Path, metavar="RESULT_DIR")
    parser.add_argument(
        "--comparison-dir",
        type=Path,
        help="also validate a cross-GPU aggregate generated by analyze_results.py",
    )
    return parser.parse_args()


def verify_sources() -> None:
    missing = sorted(path for path in REQUIRED_SOURCE_FILES if not (ROOT / path).is_file())
    if missing:
        raise AssertionError(f"missing source files: {', '.join(missing)}")


def verify_result_bundle(directory: Path, device_fragment: str) -> None:
    missing = sorted(
        name for name in REQUIRED_RESULT_FILES if not (directory / name).is_file()
    )
    if missing:
        raise AssertionError(f"{directory}: missing {', '.join(missing)}")

    metadata: dict[str, Any] = json.loads(
        (directory / "metadata.json").read_text(encoding="utf-8")
    )
    if device_fragment not in str(metadata["device"]):
        raise AssertionError(f"{directory}: unexpected device {metadata['device']!r}")

    rows = read_csv(directory / "summary.csv")
    points = {(row["workload"], int(row["cols"])) for row in rows}
    expected = {
        (workload, width)
        for workload in EXPECTED_WORKLOADS
        for width in EXPECTED_WIDTHS
    }
    if points != expected:
        raise AssertionError(f"{directory}: summary does not contain the 30 expected points")

    largest_width = [row for row in rows if int(row["cols"]) == 65536]
    if len(largest_width) != len(EXPECTED_WORKLOADS):
        raise AssertionError(f"{directory}: incomplete 64K result set")
    for row in largest_width:
        speedup = float(row["dsmem_vs_best"])
        if not math.isfinite(speedup) or speedup <= 1.0:
            raise AssertionError(
                f"{directory}: {row['workload']} is not a DSMEM win at 64K"
            )


def verify_comparison(directory: Path) -> None:
    rows = read_csv(directory / "cross_gpu_aggregate.csv")
    devices = {row["device"] for row in rows}
    if devices != {"RTX 5090", "H100"}:
        raise AssertionError(f"unexpected aggregate devices: {sorted(devices)}")
    if len(rows) != 2 * len(EXPECTED_WIDTHS):
        raise AssertionError("cross-GPU aggregate has an unexpected number of rows")


def main() -> int:
    args = parse_args()
    verify_sources()
    by_device: dict[str, Path] = {}
    for directory in args.runs:
        metadata = json.loads(
            (directory / "metadata.json").read_text(encoding="utf-8")
        )
        device = str(metadata.get("device", ""))
        label = "H100" if "H100" in device else "RTX 5090" if "5090" in device else device
        if label in by_device:
            raise AssertionError(f"duplicate device bundle: {label}")
        by_device[label] = directory
    if set(by_device) != {"RTX 5090", "H100"}:
        raise AssertionError(
            f"expected RTX 5090 and H100 bundles, got {sorted(by_device)}"
        )
    verify_result_bundle(by_device["RTX 5090"], "RTX 5090")
    verify_result_bundle(by_device["H100"], "H100")
    if args.comparison_dir is not None:
        verify_comparison(args.comparison_dir)
    print("Artifact verification passed: sources and selected result bundles.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
